language: node_js
node_js:
  - "12"

cache: yarn

install: yarn
script:
  - yarn lint
  - yarn test
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "12"
      script:
        - rm -rf dist
        - yarn build
        - cp package.json dist/package.json
        - cp README.md dist/README.md
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_token: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
